version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - prodnetwork
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: HOSTIP
#      KAFKA_CREATE_TOPICS: "topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prodnetwork
    depends_on:
      - zookeeper
  producer:
    container_name: producer
    image: miciav/producer
    environment:
       KAFKA_ADDRESS: kafka:9092
       ZK_ADDRESS: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - prodnetwork
    links:
      - kafka
  producer:
    container_name: producer
    image: miciav/producer
    environment:
       KAFKA_ADDRESS: kafka:9092
       ZK_ADDRESS: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - prodnetwork
    restart: on-failure:10
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    container_name: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 9000:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
    networks:
      - prodnetwork
  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    container_name: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 9001:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
    networks:
      - prodnetwork
  zeppelin:
    container_name: zeppelin
    image: dylanmei/zeppelin
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=1g
      MASTER: local[*]
      KAFKA_ADDRESS: kafka:9092
    depends_on:
      - kafka
      - zookeeper
      - cassandra
    links:
      - cassandra
      - master
    ports:
      - "9100:8080"
    volumes:
      - ./zeppelin/about.json:/usr/zeppelin/notebook/about.json
      - ./zeppelin/data:/usr/zeppelin/data
      - ./zeppelin/notebooks:/usr/zeppelin/notebook
      - ./zeppelin/conf:/usr/zeppelin/conf
    networks:      
      - prodnetwork
  cassandra:
    container_name: cassandra
    image: spotify/cassandra
    ports:
      - "7001:7001"
      - "7199:7199"
      - "9160:9160"
      - "7000:7000"
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:      
      - prodnetwork



